apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cerebro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cerebro.name" . }}
    helm.sh/chart: {{ include "cerebro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  configuration-file: |
    [server]
    host = 0.0.0.0
    port = 9444

    [spacy]
    model = fr_core_news_md
    iterations = 40
    min_score = 0.1
    chunk_size = 1000

    [features]
    use_mongo = true
    use_spacy = true

    [mongodb]
    url = mongo-0.mongo:27017
    database = cerebro
