apiVersion: v1
kind: Service
metadata:
  name: {{ include "cerebro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cerebro.name" . }}
    helm.sh/chart: {{ include "cerebro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cerebro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
