image: docker:stable

stages:
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  variables:
    PROJECT_NAME: "milobella"
    MODULE_NAME: ${CI_PROJECT_NAME}
    GITLAB_HOST: "gitlab.milobella.com"
    MODULE_DESCRIPTION: "Natural language understanding service of Milobella."
  script:
  # Write the id_rsa private key into the good path
  - mkdir -p private && echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private/id_rsa
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  tags: [docker,milobella]

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_LATEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
    - docker push $CONTAINER_LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION.txt)
  tags: [docker,milobella]
  only: [master]

